// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sktuttxaxryrocuhmqgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrdHV0dHhheHJ5cm9jdWhtcWd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNzkyNjQsImV4cCI6MjA2Mzk1NTI2NH0.VmgF5o7mpCpixs8OH5SlbBpvWFvAK50asxYnzaGmQdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);